# Generated by Django 4.2 on 2023-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_statement_end_date_statement_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='statement',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
