# Generated by Django 4.2 on 2023-05-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_statement_end_date_alter_statement_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': ['created_date', 'pk']},
        ),
    ]
