# Generated by Django 4.2 on 2023-05-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer_groups_customer_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_date']},
        ),
    ]
