# Generated by Django 4.2 on 2023-05-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': ['created_date', 'pk']},
        ),
    ]
